<?php $this->component('head')?>
<body>
<div class="wrapper">
    <?php if(isset($addNav) && $addNav):?>
    <nav class="mod-nav" id="scrollNav">
        <div class="wrap">
            <div class="inner">
                <?php 
                    $path = strval($_SERVER['REQUEST_URI']);
                    $val = explode("/",$path)[1];
                ?>
                <ul>
                    <li><a class="nav-item" href="/"><span>首页</span></a></li>
                    <li class="<?php echo ($val=='category')? 'active':'';?>"><a class="nav-item" href="/category/"><span>分类</span></a></li>
                    <li class="<?php echo ($val=='gift')? 'active':'';?>"><a class="nav-item" href="/gift/"><span>礼包</span></a></li>
                    <li class="<?php echo ($val=='smallgame')? 'active':'';?>"><a class="nav-item" href="/smallgame/"><span>小游戏</span></a></li>
                    <li class="<?php echo ($val=='pay')? 'active':'';?>"><a class="nav-item" href="/pay/recharge/"><span>充值</span></a></li>
                    <li class="<?php echo ($val=='notice')? 'active':'';?>"><a class="nav-item" href="/notice/"><span>活动</span></a></li>
                    <li class="<?php echo ($val=='member')? 'active':'';?>"><a class="nav-item" href="/member/sign/"><span>签到</span></a></li>
                    <li class="<?php echo ($val=='rank')? 'active':'';?>"><a class="nav-item" href="/rank/"><span>排行</span></a></li>
                </ul>
            </div> 
        </div> 
    </nav>
    <?php endif;?>
    <?php if(isset($addUsrNav) && $addUsrNav && !IS_APP): ?>
    <div class="user-header">
        <a class="back" href="<?php echo isset($_SERVER['HTTP_REFERER']) ? "javascript:history.go(-1);" : '/' ?>"></a>
        <div class="logo"><a href="/"><img src="<?php echo IMAGEURL.'h/public/'.(SHOW_QRCODE ? 'header-logo.png' : 'header-logo2.png');?>" alt="游老虎" /></a></div>
    </div>
    <?php endif; ?>
	<?php echo $body;?>
	<script type="text/javascript" src="<?php echo WEB_SCRIPT.'lib/jquery-2.2.2.min.js';?>"></script>
	<script type="text/javascript" src="<?php echo WEB_SCRIPT.'lib/sea.js';?>"></script>
	<script type="text/javascript" src="<?php echo WEB_SCRIPT.'h/plugins/fastclick.js';?>"></script>
	<script type="text/javascript">
		$(function() {
		  FastClick.attach(document.body);
		});
	</script>
	<script>
	    seajs.config({
	        base:'<?php echo rtrim(WEB_SCRIPT,'/'); ?>',
	        paths: {
	            'addScript':'<?php echo rtrim(WEB_SCRIPT,'/'); ?>'
	        },
	        map: [
	            [ /^(.*?\/script\/(?:src|dist)\/.*?\/.*?\.js$)(?:.*)$/i, '$1?v=<?php echo $this->version;?>']
	        ],
	        charset: 'utf-8'
	    });
	    seajs.use('addScript/h/common/common.js',function(){
	        <?php if (isset($addScript) && $addScript): ?>
		        <?php foreach ($addScript as $val): ?>
		        seajs.use('addScript/<?php echo $val; ?>');
		        <?php endforeach; ?>
		    <?php endif; ?>
	    });
	</script>
</div>
</body>
<?php $this->component('foot')?>