<?php $this->display('common/header.phtml');?>
<?php if(!$error['env']):?>
<div class="error-info">
<h3> Error No:</h3><div><?php echo $error["code"];?></div>
<h3>Message:</h3><div><?php echo $error["message"];?></div>
<h3>File:</h3><div><?php echo $error["file"];?></div>
<h3>Line:</h3><div><?php echo $error["line"];?></div>
<h3>Trace:</h3><pre><?php echo $error["traceAsString"];?></pre>
</div>
<?php endif;?>
<?php $this->display('common/footer.phtml')?>
