<?php $this->display('common/header.phtml')?>
<?php if($error["env"]):?>
<?php 
echo "<h1> Error No.:{$error["code"]}</h1>",
	 '<h2>Message:</h2>',
	 "<div>{$error['message']}</div>",
 	 '<h2>File:</h2>',
 	 "<div>{$error['file']}</div>",
 	 '<h2>Line:</h2>',
 	 "<div>{$error['line']}</div>",
 	 '<h2>Trace:</h2>';
 	 "<pre>{$error['traceAsString']}</pre>";
?>
<?php endif;?>
<?php $this->display('common/footer.phtml')?>
