<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>光年设计表现</title>
  <link rel="stylesheet" type="text/css" href="<?php echo WWW_STYLE; ?>bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="<?php echo WWW_STYLE; ?>base.css">
</head>
<body>
  <header>
    <div class="container">
      <h1><a class="block" href="#">光年设计表现</a></h1>
    </div>
    <div class="title-1">
      <nav class="navbar navbar-inverse navbar-static-top" >
        <div class="container">
          <ul class="nav navbar-nav ">
            <li class="nav-x"><a href="show.html">店铺首页</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="product.html">服务项目</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x active"><a href="work.html">作品展示</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="record.html">交易记录</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="">交易评价</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="">交易保障</a></li>
          </ul>
        </div>
      </nav>
    </div>
  </header>
  <div class="main">
    <div class="content container">
      <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
          <div class="item active center-block">
            <p class="text-center">项目名称：公共空间售楼部</p>
            <img class="center-block" src="<?php echo WWW_IMAGE; ?>log1.jpg" alt="第一张">
          </div>
          <div class="item">
            <p class="text-center">项目名称：公共空间售楼部</p>
            <img class="center-block" src="<?php echo WWW_IMAGE; ?>log2.jpg" alt="第二张">
          </div>
          <div class="item">
            <p class="text-center">项目名称：公共空间售楼部</p>
            <img class="center-block" src="<?php echo WWW_IMAGE; ?>log3.jpg" alt="第三张">
          </div>
          <div class="item">
            <p class="text-center">项目名称：公共空间售楼部</p>
            <img class="center-block" src="<?php echo WWW_IMAGE; ?>log4.jpg" alt="第四张">
          </div>
          <div class="item">
            <p class="text-center">项目名称：公共空间售楼部</p>
            <img class="center-block" src="<?php echo WWW_IMAGE; ?>log5.jpg" alt="第五张">
          </div>
          <div class="item">
            <p class="text-center">项目名称：公共空间售楼部</p>
            <img class="center-block" src="<?php echo WWW_IMAGE; ?>log6.jpg" alt="第六张">
          </div>
        </div>
        <a href="#myCarousel" data-slide="prev" class="carousel-control left">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a href="#myCarousel" data-slide="next" class="carousel-control right">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
  <footer id="footer" class="text-muted">
      <div class="container">
        <p>企业培训 | 合作事宜 | 版权投诉</p>
        <p>苏ICP备12345678. © 2009-2016 装潢网. Powered by Bootstrap.</p>
      </div>  
  </footer>
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="<?php echo WWW_SCRIPT; ?>bootstrap.min.js"></script>
</body>
</html>