<?php
    $this->setTitle('我的游戏礼包_游老虎')
        ->setValue('usrNav', TRUE)
        ->setStyles('h/member/record/gift.css')
        ->setFootScripts('h/public/itemlink.js');
?>
<div class="container">
    <div class="mod-list">
        <div class="hd">我的礼包</div>
        <?php if(isset($lists) && $lists): ?>
        <div class="bd">
            <ul>
            <?php foreach($lists as $list):?>
                <li><a class="link" href="/gift/detail/?id=<?php echo $list['id']?>" data-code="<?php echo $list['code']; ?>">
                    <div class="pic"><img src="<?php echo URL_IMAGE.$list['logo'];?>" alt=""></div>
                    <div class="cont">
                        <h3><?php echo $list['giftName']; ?></h3>
                        <p class="description"><?php echo $list['gameName']; ?></p>
                    </div>
                    <div class="button"><span class="btn-start">查看</span></div>
                </a></li>
            <?php endforeach;?>
            </ul>
        </div>
        <?php else:  ?>
            <?php $this->setValue('notify', '您还没有礼包记录哦！')->component('empty'); ?>
        <?php endif; ?>
    </div>
    <?php if($recommendArr):?>
    <div class="mod-recommend">
        <div class="hd">推荐礼包</div>
        <div class="bd">
            <ul>
                <?php foreach($recommendArr as $recommend):?>
                <li>
                    <a href="/gift/detail/?id=<?php echo $recommend['id']; ?>" data-code="">
                        <img src="<?php echo URL_IMAGE.$recommend['logo'];?>" alt="">
                        <span class="txt"><?php echo $recommend['giftName']; ?></span>
                    </a>
                </li>
                <?php endforeach; ?> 
            </ul>
        </div>
    </div>
    <?php endif;?>
</div>