<?php
    $this->display("elements/header.phtml", array(
        'title'=> '我的充值记录-'.WEB_TITLE,
        'addStyle' => array('h/member/record/recharge.css')
    ));
?>
<div class="container">
    <?php if(isset($lists) && $lists):?>
    <div id="rechargeList" class="mod-recharge">
        <ul>
            <?php foreach($lists as $key=>$list):?>
            <li class="list-item">
                <div class="hd">
                    <?php $type=array('1'=>'游戏充值', '2'=>'账号充值') ; echo $type[$list['type']]; ?>
                    <span class="order-number">订单号：<span class="num"><?php echo $list['id']; ?></span></span>
                </div>
                <div class="bd">
                    <div class="pic"><img src="<?php echo IMAGEURL,$list['logo'];?>" alt=""></div>
                    <div class="cont">
                        <p class="title"><?php echo $list['name']?><?php echo $list['service'] ? "（{$list['service']}服）" : NULL; ?></p>
                        <p class="time"><?php echo $list['status'] == 2 ? date('Y-m-d H:i:s', strtotime($list['paytime'])) : date('Y-m-d H:i:s', strtotime($list['addtime'])); ?></p>
                    </div>
                    <div class="pay <?php $cssStatus=array('pending', 'failed', 'success'); echo $cssStatus[$list['status']];?>">
                        <p class="amount">￥<span class="num"><?php echo number_format($list['price'], 2); ?></span>元</p>
                        <p class="status">
                            <?php if($list['status'] == 0): ?>
                                <span class="txt">待付款</span>
                                <a href="javascript:;" class="btn-pay" rel="nofollow">查看</a>
                            <?php elseif($list['status'] == 1): ?>
                                <span class="txt">交易失败</span>
                            <?php else: ?>
                                <span class="txt">交易成功</span>
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            </li>
            <?php endforeach;?>
        </ul>
        <?php if(count($lists) >= 10):?>
        <div id="more" class="mod-more">点击加载更多</div>
        <?php endif;?>
    </div>
    <?php else: ?>
        <?php $this->display("elements/default.phtml",array('defaultMsg'=>'您还没有充值记录哦！')); ?>
    <?php endif; ?>
</div>
<?php
    $this->display("elements/footer.phtml", array(
        'addScript' => array('h/member/record/recharge.js')
    ));
?>