<?php $this->setTitle('我的红包_游老虎')->setStyles('h/member/redpackage/index.css')->setFootScripts('h/member/redpackage/index.js'); ?>
<div class="container">
	<div class="mod-redpackage">
		<div id="tabType" class="redpackage-type">
			<span class="type active" data-type="1">未使用</span>
			<span class="type" data-type="2">已使用/已过期</span>
		</div>
		<div id="redpkList" class="redpackage">
			<ul>
			</ul>
		</div>
	</div>
</div>
