<style>

*{
	margin:0;
	padding:0;
	font-size:14px;
}

a {
	text-decoration:none;
}

#page a {
    padding: 2px 10px;
    background-color: #fdfdfd;
    border: 1px solid #eaeaea;
}
#page span, #page a {
    margin-left: 9px;
    color: #666;
}

#page .current {
    padding: 3px 10px;
    border: none;
    color: #fff;
    background-color: #df2e31;
}
#page span, #page a {
    margin-left: 9px;
    color: #666;
}
</style>

<?php if(!$page['over']):?>
<div id="page">
<!-- 首页 -->
<?php if(isset($page['first'])):?>
<a href="<?php echo $page['url']?>1">首页</a>
<?php endif;?>
<!-- 首页 -->
<!-- 上一页 -->
<?php if(isset($page['prev'])):?>
<a href="<?php echo $page['url'],$page['prev']?>"><<</a>
<?php endif;?>
<!-- 上一页 -->
<!-- 中间区间页数 -->
<?php for(;$page['start']<$page['end']; $page['start']++):?>
<?php if($page['start'] == $page['page']):?>
<span class="current"><?php echo $page['start'];?></span>
<?php else:?>
<a href="<?php echo $page['url'],$page['start']?>"><?php echo $page['start'];?></a>
<?php endif;?>
<?php endfor;?>
<!-- 中间区间页数 -->
<!-- 下一页 -->
<?php if(isset($page['next'])):?>
<a href="<?php echo $page['url'],$page['next']?>">>></a>
<?php endif;?>
<!-- 下一页 -->
<!-- 末页 -->
<?php if(isset($page['last'])):?>
<a href="<?php echo $page['url'],$page['last']?>">末页</a>
<?php endif;?>
<!-- 末页 -->
<label>&nbsp;&nbsp;&nbsp;共<?php echo $page['count']?>条,<?php echo $page['limit']?>条/页, 当前第<?php echo $page['page']?>页, 共<?php echo $page['pageTotal']?>页</label>
</div>
<?php endif;?>