<?php $this->display('shop/elements/header.phtml')?>
  <div class="main">
    <div class="container">
       <div class="top">
          <div class="media left">
             <div class="media-left">
                <img src="<?php echo WWW_IMAGE; ?>show_small1.jpg" class="media-object">
             </div>
             <div class="media-body">
                <h3 class="media-heading text-center">工装效果图</h3>
                <div class="price text-center">
                    <p><small>价格：</small>&nbsp;￥500元/张</p>
                </div>
                <table class="evaluate table text-center">
                    <tr>
                      <td></td>
                      <td><span>0.00</span></td>
                      <td>服务态度:<span>0.00</span>分</td>
                    </tr>
                    <tr>
                      <td>评分</td>
                      <td><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span></td>
                      <td>工作速度:<span>0.00</span>分</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>(0条评论)</td>
                      <td>完成质量:<span>0.00</span>分 </td>
                    </tr>
                </table>
                <table class="average table table-bordered text-center">
                    <tr>
                      <td><p>累计交易金额</p><h4>￥1,300.00</h4></td>
                      <td><p>累计购买次数</p><h4>1次</h4></td>
                    </tr>
                </table>
                <button class="btn btn-lg btn-danger buy center-block">立即购买</button>
             </div>
          </div> 
       </div>
       <div class="middle">
         <div class="case-left">
           <h4>服务案例</h4><hr>
           <div class="row row-case">
           	  <?php for($i=1; $i<5; $i++):?>		
              <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div>
                  <a href="/product/<?php echo $i?>.html" target="_blank" title=""><img src="<?php echo WWW_IMAGE; ?>show_small<?php echo $i%2+1?>.jpg"></a>
                  <p class="case-title text-center" >中式平层卧室</p>
                </div>
              </div>
              <?php endfor;?>
            </div>
         </div>
       </div>
       <div class="bottom-1">
          <div class="server">
             <h4>服务详情</h4><hr>
             <div class="ser-con">
                  <p>暂无详细介绍</p>
             </div>
          </div>
       </div>
       <div class="bottom-2">
          <div class="evaluate">
              <ul class="nav nav-tabs" id="nav">
                 <li class="active"><a href="#record">购买记录</a></li>
                 <li><a href="#user">客户评价</a></li>
             </ul>
             <div class="tab-content" style="padding:10px">
                   <div class="tab-pane active fade in" id="record">
                      <table class="table text-center">
                         <thead>
                           <tr>
                              <th>订单类型</th>
                              <th>图纸数量</th>
                              <th>订单价格</th>
                              <th>客户</th>
                              <th>下单时间</th>
                           </tr>
                         </thead>
                         <tbody>
                           <tr>
                             <td>工装效果图</td>
                             <td>3</td>
                             <td>1300.00</td>
                             <td>w*****x</td>
                             <td>2016-4-1 15:58</td>
                           </tr>
                         </tbody>
                      </table>
                   </div>
                   <div class="tab-pane fade" id="user">
                       <p>暂无评价</p>
                   </div>
             </div>
          </div>
       </div>
    </div>
  </div>
  <footer id="footer" class="text-muted">
      <div class="container">
        <p>企业培训 | 合作事宜 | 版权投诉</p>
        <p>苏ICP备12345678. © 2009-2016 装潢网. Powered by Bootstrap.</p>
      </div>  
  </footer>
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript">
    $('#nav a').on('click', function(e){
          e.preventDefault();
          $(this).tab('show');
     });
</script>
</body>
</html>