 <?php $this->display('shop/elements/header.phtml')?>
  <div class="main">
    <div class="content container">      
      <div class="page text-center">
        <ul class="type nav nav-justified">
          <li class="type-x">按类别检索：</li>
          <li class="type-x"><a class="sel" href="#">全部</a></li>
          <li class="type-x"><a href="#">家装</a></li>
          <li class="type-x"><a href="#">工装</a></li>
          <li class="type-x"><a href="#">建筑</a></li>
          <li class="type-x"><a href="#">其他</a></li>
        </ul>
      </div>
      <div class="picture">
      	<?php for($i=0;$i<3;$i++):?>
        <div class="row row-work">
          <?php for($k=1; $k<5; $k++):?>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="/product/<?php echo $k;?>.html" title=""><img src="<?php echo WWW_IMAGE; ?>show_small<?php echo $k;?>.jpg"></a>
              <div class="caption">
                <p><a href="display.html" target="_blank" title="">中式平层卧室</a></p>
              </div>
            </div>
          </div>
          <?php endfor;?>          
        </div>
        <?php endfor;?>
      </div>
      <div class="paging  text-center">
        <ul class="pagination pagination-lg ">
          <li><a href="">&laquo;</a></li>
          <li class="active"><a href="">1</a></li>
          <li><a href="">2</a></li>
          <li><a href="">3</a></li>
          <li><a href="">4</a></li>
          <li><a href="">5</a></li>
          <li><a href="">...</a></li>
          <li><a href="">&raquo;</a></li>
        </ul>
      </div>
    </div>
  </div>
  <footer id="footer" class="text-muted">
      <div class="container">
        <p>企业培训 | 合作事宜 | 版权投诉</p>
        <p>苏ICP备12345678. © 2009-2016 装潢网. Powered by Bootstrap.</p>
      </div>  
  </footer>
</body>
</html>