<?php $this->display('shop/elements/header.phtml')?>
  <div class="main">
    <div class="content container">
      <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>订单类型</th>
              <th>图纸数量(张)</th>
              <th>订单价格(元)</th>
              <th>客户</th>
              <th>下单时间</th>
            </tr>
          </thead>
          <tbody>
             <tr class="active">
                <td>家装效果图</td>
                <td>3</td>
                <td>400.00</td>
                <td>c****i</td>
                <td>2016-4-1 16:54</td>
             </tr>
             <tr class="info">
                <td>家装效果图</td>
                <td>3</td>
                <td>400.00</td>
                <td>c****i</td>
                <td>2016-4-1 16:54</td>
              </tr>
              <tr class="active">
                <td>家装效果图</td>
                <td>3</td>
                <td>400.00</td>
                <td>c****i</td>
                <td>2016-4-1 16:54</td>
              </tr>
              <tr class="info">
                <td>家装效果图</td>
                <td>3</td>
                <td>400.00</td>
                <td>c****i</td>
                <td>2016-4-1 16:54</td>
              </tr>
              <tr class="active">
                <td>家装效果图</td>
                <td>3</td>
                <td>400.00</td>
                <td>c****i</td>
                <td>2016-4-1 16:54</td>
              </tr>
          </tbody>
       </table>
    </div>
  </div>
  <footer id="footer" class="text-muted">
      <div class="container">
        <p>企业培训 | 合作事宜 | 版权投诉</p>
        <p>苏ICP备12345678. © 2009-2016 装潢网. Powered by Bootstrap.</p>
      </div>  
  </footer>
</body>
</html>