<?php $this->display('shop/elements/header.phtml')?>
  <div class="main">
    <div class="content container">      
      <div class="picture-1">
        <div class="row row-show1">
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="detail.html" title=""><img src="<?php echo WWW_IMAGE; ?>show1.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="detail.html">立即购买</a>
                </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show2.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show3.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show4.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
        </div>
        <div class="row row-show1">
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show1.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show2.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show3.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
              <a href="#" title=""><img src="<?php echo WWW_IMAGE; ?>show4.jpg"></a>
                <div class="caption">
                  <h4>500元/张</h4>
                  <p>工装效果图</p>
                  <small>成交:1次</small>
                  <a class="btn btn-danger" href="">立即购买</a>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer id="footer" class="text-muted">
      <div class="container">
        <p>企业培训 | 合作事宜 | 版权投诉</p>
        <p>苏ICP备12345678. © 2009-2016 装潢网. Powered by Bootstrap.</p>
      </div>  
  </footer>
</body>
</html>