<?php $this->display('layout/header.phtml');?>
<body>
<?php if(!$data['env']):?>
<div class="error-info">
<h3> Error No:</h3><div><?php echo $data['code'];?></div>
<h3>Message:</h3><div><?php echo $data['message'];?></div>
<h3>File:</h3><div><?php echo $data['file'];?></div>
<h3>Line:</h3><div><?php echo $data['line'];?></div>
<h3>Trace:</h3><pre><?php echo $data['traceAsString'];?></pre>
</div>
<?php endif;?>
</body>
<?php $this->display('layout/footer.phtml')?>