<!DOCTYPE html>
<html lang="zh-cn">
<head>
<title><?php echo empty($title) ?  '标题' : $title; ?></title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="renderer" content="webkit"/>
<?php if(!empty($metas)) { foreach($metas as $meta): #meta_start?>
<meta name="<?php echo $meta['name']?>" content="<?php echo $meta['content'] ;?>"/>
<?php endforeach; }; #meta_end?>

<link rel="stylesheet" href="<?php echo RESOURCE_STYLE?>bootstrap.min.css" />
<link rel="stylesheet" href="<?php echo RESOURCE_STYLE?>font-awesome.min.css" />
<link rel="stylesheet" href="<?php echo RESOURCE_STYLE?>googlefonts.css" />
<link rel="stylesheet" href="<?php echo RESOURCE_STYLE?>ace.min.css" />
<link rel="stylesheet" href="<?php echo RESOURCE_STYLE?>ace-rtl.min.css" />
<?php if(!empty($styles)) { foreach($styles as $style): #样式_start?>
<link href="<?php echo RESOURCE_STYLE.$style; ?>" rel="stylesheet" type="text/css" />
<?php endforeach; }; #样式_end?>
<!--[if IE 7]>
<link rel="stylesheet" href="admin/css/font-awesome-ie7.min.css" />
<![endif]-->		
<!--[if lte IE 8]>
<link rel="stylesheet" href="admin/css/ace-ie.min.css" />
<![endif]-->

<!--[if !IE]> -->
<script src="<?php echo RESOURCE_SCRIPT?>jquery.2.0.3.min.js"></script>
<!-- <![endif]-->
<!--[if IE]>
<script src="<?php echo RESOURCE_SCRIPT?>jquery.1.10.2.min.js"></script>
<![endif]-->
<script src="<?php echo RESOURCE_SCRIPT?>bootstrap.min.js"></script>
<script type="text/javascript">
	if("ontouchend" in document) document.write("<script src='<?php echo RESOURCE_SCRIPT?>jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>
<!--[if lt IE 9]>
<script src="<?php echo RESOURCE_SCRIPT?>html5shiv.js"></script>
<script src="<?php echo RESOURCE_SCRIPT?>respond.min.js"></script>
<![endif]-->
<?php if(!empty($scripts)) { foreach($scripts as $script): #脚本_start?>
<script type="text/javascript" src="<?php echo RESOURCE_SCRIPT.$script; ?>"></script>
<?php endforeach; }; #脚本_end?>
</head>