<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit"/>'
    <?php if(!empty($metas)) { foreach($metas as $meta): #meta_start?>
	<meta name="<?php echo $meta['name']?>" content="<?php echo $meta['content'] ;?>"/>
	<?php endforeach; }; #meta_end?>
    <title><?php echo empty($title) ?  '标题' : $title; ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo ADMIN_STYLE?>common/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo ADMIN_STYLE?>common/neon-core.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo ADMIN_STYLE?>common/neon-theme.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo ADMIN_STYLE?>common/neon-forms.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo ADMIN_STYLE?>common/entypo.css">
    <link rel="stylesheet" type="text/css" href="<?php echo ADMIN_STYLE?>common/custom.css">
    <?php if(!empty($styles)) { foreach($styles as $style): #样式_start?>
	<link href="<?php echo ADMIN_STYLE.$style; ?>" rel="stylesheet" type="text/css" />
	<?php endforeach; }; #样式_end?>	
	<script src="<?php echo ADMIN_SCRIPT?>common/jquery.min.js"></script>
	<script src="<?php echo ADMIN_SCRIPT?>common/bootstrap.min.js"></script>
	<!--[if lt IE 9]>
	<script src="<?php echo ADMIN_SCRIPT?>html5shiv.js"></script>
	<script src="<?php echo ADMIN_SCRIPT?>respond.min.js"></script>
	<![endif]-->
	<?php if(!empty($scripts)) { foreach($scripts as $script): #脚本_start?>
	<script type="text/javascript" src="<?php echo ADMIN_SCRIPT.$script; ?>"></script>
	<?php endforeach; }; #脚本_end?>
</head>