<div class="sidebar" id="sidebar">
	<ul class="nav nav-list">
		<li>
			<a href="/admin/index/index">
				<i class="icon-dashboard"></i>
				<span class="menu-text">控制台</span>
			</a>
		</li>
		<li class="active open">
			<a href="javascript:void(0);" class="dropdown-toggle">
				<i class="icon-user"></i>
				<span class="menu-text">用户管理</span>

				<b class="arrow icon-angle-down"></b>
			</a>
			<ul class="submenu">
				<li>
					<a href="/admin/user/member"><i class="icon-double-angle-right"></i>买家管理</a>
				</li>
				<li class="active">
					<a href="/admin/user/member"><i class="icon-double-angle-right"></i>商户管理</a>
				</li>						
			</ul>						
		</li>
		<li>
			<a href="/admin/shop/index">
				<i class="icon-inbox"></i>
				<span class="menu-text"> 店铺管理 </span>
			</a>
		</li>
		<li>
			<a href="/admin/picture/index">
				<i class="icon-picture"></i>
				<span class="menu-text"> 效果图管理 </span>
			</a>
		</li>
		<li>
			<a href="/admin/setting/index">
				<i class="icon-cog"></i>
				<span class="menu-text"> 系统设置 </span>
			</a>
		</li>
	</ul>
	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>
</div>