<?php $this->display('layout/header.phtml', array('title'=>'管理员_列表'))?>
<body class="page-body loaded">
	<div class="page-container">
		<?php $this->display('layout/left.phtml')?>
		<div class="main-content" style="min-height: 947px;">
			<?php $this->display('layout/user.phtml')?>
			<div class="navbar-collapse"></div>
			<div class="dataTables_wrapper"></div>
			<div class="navbar-collapse">
				<p><a class="btn btn-green" href="javascript:;">添加</a></p>
			</div>
			<div class="dataTables_wrapper">
			    <table id="dataTable-user" class="table table-condensed table-bordered table-hover">
			        <thead>
			            <tr>
			                <th class="text-center">ID</th>
			                <th>管理员名称</th>
			                <th>登录帐号</th>
			                <th>用户组</th>
			                <th>状态</th>
			                <th>操作</th>
			            </tr>
			        </thead>
			        <tbody>
			        	<?php foreach($pagitor['lists'] as $list):?>
						<tr>
							<td class="text-center"><?php echo $list->id; ?></td>
							<td><?php echo $list->nickname; ?></td>
							<td><?php echo $list->username; ?></td>
							<td>超级管理员</td>
							<?php $status = array('0'=>'entypo-lock-open','-1'=>'entypo-lock');?>
							<td><i class="<?php echo $status[$list->status] ?>"></i></td>
							<td><a class="btn btn-blue" href="http://op.yesyungou.com/admin/administrator/edit/?id=1">修改</a>&nbsp;&nbsp;<a class="btn btn-red" href="http://op.yesyungou.com/admin/administrator/del/?id=1" onclick="return confirm(&#39;确定删除?&#39;);">删除</a></td>
						</tr>
						<?php endforeach; ?>
					</tbody>
			    </table>
			    <?php $this->display('layout/page.phtml'); ?>
			</div>
        </div>
	</div>
</body>
<?php $this->display('layout/footer.phtml');
?>