<div class="dataTables_wrapper">
	<table id="dataTable-user"
		class="table table-condensed table-bordered table-hover">
		<thead>
			<tr>
				<th class="text-center">ID</th>
				<th class="text-center">账号</th>
				<th class="text-center">昵称</th>
				<th class="text-center">状态</th>
				<th class="text-center">添加时间</th>
				<th class="text-center">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($pagitor['lists'] as $list):?>
			<tr>
				<td class="text-center"><?php echo $list['id'];?></td>
				<td class="text-center"><?php echo $list['username'];?></td>
				<td class="text-center"><?php echo $list['nickname'];?></td>
				<td class="text-center"><i class="entypo-lock<?php echo $list['status'] == 'enable' ? '-open' : NULL ?>"></i></td>
				<td class="text-center"><?php echo $this->formatDate($list['addtime']);?></td>
				<td class="text-center">
					<button class="btn btn-danger" data-id="<?php echo $list['id'];?>">修改</button>
				</td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	<?php $this->component('page');?>
</div>