<?php $this->moduleLayout('header.phtml', array('title'=>'服务器帅炸了〒▽〒'));?>
<?php if(!$notify['env']):?>
<dl class="dl-horizontal">
  <dt>Error No:</dt>
  <dd><?php echo $notify["code"];?></dd>
  <dt>Message:</dt>
  <dd><?php echo $notify["message"];?></dd>
  <dt>File:</dt>
  <dd><?php echo $notify["file"];?></dd>
  <dt>Line:</dt>
  <dd><?php echo $notify["line"];?></dd>
  <dt>Trace:</dt>
  <dd><pre><?php echo $notify["traceAsString"];?></pre></dd>
</dl>
<?php endif;?>
<h1 class="text-center"><?php echo $notify["message"]; ?></h1>
<?php $this->moduleLayout('footer.phtml')?>