<?php $this->setTitle('游老虎_用户中心')->setStyles('h/member/index.css'); ?>
<div class="container">
    <div class="mod-info">
        <div class="user">
            <a href="<?php echo $this->UID ? '/member/info/index/' : '/login/' ?>">
                <span class="avatar">
                    <img onerror="this.src='<?php echo URL_IMAGE.'h/member/default_avatar.png';?>';this.onerror=null" src="<?php echo isset($userArr) && $userArr ?  $userArr['avatarhd'] : URL_IMAGE.'h/member/default_avatar.png';?>" alt="头像">
                </span>
                <span class="info">
                    <span class="name"><?php echo isset($userArr['nickname']) ? $userArr['nickname'] : '立即登录';?></span>
                    <span class="coin">
                        <?php if(isset($userArr['nickname'])): ?>
                        余额：<?php echo isset($userArr['coin']) ? $userArr['coin'] : 0;?> 金币
                        <?php else: ?>
                            登录后可享受更多特权
                        <?php endif; ?>
                    </span>
                </span>
            </a>
        </div>
        <ul>
            <li><a href="/member/record/game/"><i class="ic-recent"></i>最近在玩</a></li>
            <li><a href="/member/record/collection/"><i class="ic-collect"></i>我的收藏</a></li>
            <li><a href="/member/record/gift/"><i class="ic-gifts"></i>我的礼包</a></li>
        </ul>
        <ul>
            <li><a href="/member/record/recharge/"><i class="ic-recharge"></i>充值记录</a></li>
            <li><a href="/member/record/goldcoin/"><i class="ic-balance"></i>金币明细</a></li>
            <li><a href="/member/record/redpackage/"><i class="ic-redpakage"></i>我的红包</a></li>
        </ul>
        <ul>
            <li><a href="/help/"><i class="ic-about"></i>关于我们</a></li>
        </ul>
    </div>
</div>