<?php
    $this->setTitle('游老虎_用户登录')->setValue('usrNav', TRUE)->setStyles('h/login/index.css')->setFootScripts('h/login/index.js');
?>
<div class="container">
    <div class="mod-login">
        <input id="redirectUri" type="hidden" value="<?php echo $redirectUri; ?>" />
        <div id="tabsMain" class="mod-panel">
            <div class="tabs js-tabs">
                <div class="tab-item active"><a href="javascript:;" rel="nofollow">用户登录</a></div>
                <div class="tab-item"><a href="javascript:;" rel="nofollow">新用户注册</a></div>
            </div>
            <div class="panels js-panels">
                <div class="panel active">
                    <div id="formUserLogin" class="form-wrap"<?php echo $isUseCaptcha ? ' data-captcha="1"' : '';?>>
                        <div class="form-item form-item-user">
                            <input id="lUser" class="input-model" type="text" placeholder="请输入用户名或手机号" autocomplete="off" autocapitalize="off" />
                            <span class="clear-input"></span>
                        </div>
                        <div class="form-item form-item-password">
                            <input id="lPassword" class="input-model" type="password" placeholder="请输入密码" autocomplete="off" />
                            <span class="clear-input"></span>
                            <span class="show-pwd js-show-pwd"></span>
                        </div>
                        <div class="form-item form-item-captcha<?php echo $isUseCaptcha ? '': ' hide';?>">
                            <input id="lUserCaptcha" class="input-model" type="tel" placeholder="请输入验证码" maxlength="4" autocomplete="off"/>
                            <a id="lUserCaptchaWrap" class="captcha-wrap"><img src="<?php echo $isUseCaptcha ? '/image/captcha/?c=ulogin': URL_IMAGE.'h/public/empty.gif' ;?>" alt="验证码" /></a>
                            <span class="clear-input"></span>
                        </div>
                        <div class="other-link"><a id="toCodeLogin" class="link-type" href="javascript:;" rel="nofollow">手机动态码登录</a><a class="forget-pwd" href="/forget/<?php echo $redirectUri ? "?redirectUri={$redirectUri}" : NULL ?>">忘记密码？</a></div>
                        <div class="btn-wrap"><a id="userLoginBtn" class="submit-btn" href="javascript:;" rel="nofollow">登录</a></div>
                    </div>
                    <div id="formCodeLogin" class="form-wrap hide">
                        <div class="form-item form-item-user">
                            <input id="mobile" class="input-model" type="tel" placeholder="请输入你的手机号码" maxlength='11' autocomplete="off" />
                            <span class="clear-input"></span>
                        </div>
                        <div class="form-item form-item-captcha">
                            <input id="codeCaptcha" class="input-model" type="tel" placeholder="请输入验证码" maxlength="4" autocomplete="off"/>
                            <a class="captcha-wrap"><img src="<?php echo '/image/captcha/?c=mlogin';?>" /></a>
                            <span class="clear-input"></span>
                        </div>
                        <div class="form-item form-item-code">
                            <input id="lCode" class="input-model" type="tel" placeholder="请输入短信验证码" maxlength="4" autocomplete="off" />
                            <a id="sendcode" href="javascript:;" rel="nofollow">发送短信验证码</a>
                            <span class="clear-input"></span>
                        </div>
                        <div class="other-link"><a id="toUserLogin" class="link-type" href="javascript:;" rel="nofollow">普通登录</a></div>
                        <div class="btn-wrap"><a id="codeLoginBtn" class="submit-btn" href="javascript:;" rel="nofollow">登录</a></div>
                    </div>
                </div>
                <div class="panel">
                    <div id="formReg" class="form-wrap">
                        <div class="form-item form-item-user">
                            <input id="rUser" class="input-model" type="text" placeholder="请输入用户名或手机号" autocomplete="off" autocapitalize="off" />
                            <span class="clear-input"></span>
                        </div>
                        <div class="form-item form-item-password">
                            <input id="rPassword" class="input-model" type="password" placeholder="请输入密码" autocomplete="off" />
                            <span class="clear-input"></span>
                            <span class="show-pwd js-show-pwd"></span>
                        </div>
                        <div class="form-item form-item-captcha">
                            <input id="rUserCaptcha" class="input-model" type="tel" placeholder="请输入验证码" maxlength="4" autocomplete="off"/>
                            <a class="captcha-wrap"><img src="<?php echo  '/image/captcha/?c=ureg';?>" /></a>
                            <span class="clear-input"></span>
                        </div>
                        <div class="other-link"><div class="protocol">我已阅读并同意<a href="/help/agreement/">游老虎用户协议</a></div></div>
                        <div class="btn-wrap"><a id="regBtn" class="submit-btn" href="javascript:;" rel="nofollow">立即注册</a></div>
                    </div>
                    <div id="codeSendForm" class="form-wrap hide">
                        <div class="code-tip">短信验证码已发送至 <span id="sendToMobile"></span></div>
                        <div class="form-item form-item-code form-item-code-large">
                            <input id="rCode" class="input-model" type="tel" placeholder="请输入短信验证码" maxlength="4" autocomplete="off" />
                            <span class="clear-input"></span>
                        </div>
                        <div id="resend" class="resend button-disabled">重新发送</div>
                        <div class="btn-wrap"><a id="doneBtn" class="submit-btn" href="javascript:;" rel="nofollow">完成</a></div>
                    </div>
                </div>
            </div>
        </div>   
        <div class="mod-oauth">
            <div class="hd"><span>第三方登录</span></div>
            <div class="bd">
                <ul>
                <?php if(!$this->isFromWeixinApp):?>
                    <li><a href="<?php echo MYURL?>member/oauthqq/login/<?php echo $redirectUri ? "?redirectUri={$redirectUri}" : NULL ?>"><span class="ic-qq"></span><p class="txt">QQ登录</p></a></li>
                <?php endif;?>
                <?php if(!$isFormMobile):?>
                    <li><a href="<?php echo MYURL?>member/wxoauth/wxweb/<?php echo $redirectUri ? "?redirectUri={$redirectUri}" : NULL ?>"><span class="ic-weixin"></span><p class="txt">微信登录</p></a></li>
                <?php endif;?>
                    <!-- <li><a href="javascript:;"><span class="ic-weibo"></span><p class="txt">新浪微博登录</p></a></li> -->
                </ul>
            </div>
        </div>
    </div>
</div>