<?php $this->display('layout/header.phtml', array('styles'=>array('module/login/index.css')))?>
<body class="page-body login-page login-form-fall loaded login-form-fall-init">
    <div class="login-container">
        <div class="login-header login-caret">
            <div class="login-content">
                <a href="#" class="logo">
                    <img alt="Logo" src="image/logo.png"></a>
            </div>
        </div>
        <div class="login-form">
            <div class="login-content">
                <div class="form-login-error none"></div>
                <form id="form_login" role="form" method="post" novalidate="novalidate">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"> <i class="entypo-user"></i>
                            </div>
                            <input type="text" placeholder="用户名" id="username" name="username" class="form-control" tabindex="1" value=""></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"> <i class="entypo-key"></i>
                            </div>
                            <input type="password" placeholder="密码" id="password" name="password" class="form-control" value="" tabindex="2"></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="entypo-pencil"></i>
                            </div>
                            <input id="checkCode" class="form-control" autocomplete="off" type="text" name="captcha" tabindex="3" placeholder="验证码" maxlength="6">
                            <img class="checkImg" data-src="/admin/captcha/login" src="/admin/captcha/login" width="122" height="50"></div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block btn-login" type="button">登录</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
<?php $this->display('layout/footer.phtml', array('scripts'=>array('common/enychen.js', 'module/login/index.js')))?>