<?php $this->display('common/header.phtml', array('styles'=>array('module/login/index.css')))?>
<body class="page-body login-page login-form-fall loaded login-form-fall-init">
    <div class="login-container">
        <div class="login-header login-caret">
            <div class="login-content">
                <a href="#" class="logo">
                    <img alt="Logo" src="image/logo.png"></a>
            </div>
        </div>
        <div class="login-form">
            <div class="login-content">
            	<?php if($error):?>
                <div class="form-login-error">
                    <p><?php echo $error; ?></p>
                </div>
                <?php endif;?>
                <form id="form_login" role="form" method="post" novalidate="novalidate">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"> <i class="entypo-user"></i>
                            </div>
                            <input type="email" placeholder="用户名" id="username" name="email" class="form-control" tabindex="1"></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"> <i class="entypo-key"></i>
                            </div>
                            <input type="password" placeholder="密码" id="password" name="password" class="form-control" tabindex="2"></div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="entypo-pencil"></i>
                            </div>
                            <input id="checkCode" class="form-control" autocomplete="off" type="text" name="captcha[code]" tabindex="3" placeholder="验证码" maxlength="6">
                            <img class="checkImg" src="/admin/image/captcha?w=122&h=50&c=login" width="122" height="50"></div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block btn-login" type="submit">登录</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</body>
<?php $this->display('common/footer.phtml', array('scripts'=>array('module/login/index.js')))?>
</html>