<?php
    $this->setTitle('游老虎_游戏分类')
        ->setValue('nav', TRUE)
        ->setStyles('h/category/detail.css')
        ->setFootScripts('h/category/detail.js');
?>
<div class="container">
    <div id="catelistScroll" class="mod-catelist">
        <div class="inner">
            <ul>
            <?php foreach ($categoryArr as $category):?>
                <li<?php echo $id == $category->getId() ? ' class="active"' : ''?>><a href="/category/detail/?id=<?php echo $category->getId(); ?>">
                    <span class="ic-cate"><img src="<?php echo URL_IMAGE.trim($category->getLogo(), '/');?>" alt=""/></span>
                    <span class="txt"><?php echo $category->getName(); ?></span>
                </a></li>
            <?php endforeach;?>
            </ul>
        </div>
    </div>
    <?php if(isset($gameArr) && $gameArr): ?>
    <div id="gameList" class="mod-gamelist">
        <ul>
        <?php foreach ($gameArr as $game):?>
            <li class="j-link" data-gameid="<?php echo $game['id']?>">
                <div class="pic"><img src="<?php echo URL_IMAGE.$game['logo'];?>" alt="" /></div>
                <div class="cont">
                    <h3><?php echo $game['name']; ?><?php if($game['hasGift']):?><span class="gift">礼包</span><?php endif;?><?php if($game['is_recommend']):?><span class="hot">热门</span><?php endif;?>
                    </h3>
                    <p class="desc"><?php echo $game['intro']; ?></p>
                </div>
                <div class="button"><a class="btn-start" href="/<?php echo $game['id']; ?>.html">进入</a></div>
            </li>
        <?php endforeach;?>
        </ul>
        <?php if(count($gameArr) >=10): ?>
        <div id="more" class="mod-more">点击加载更多</div>
        <?php endif; ?>
    </div>
    <?php else: ?>
        <?php $this->setValue('notify', '还没有该系列游戏哦！')->component('empty'); ?>
    <?php endif; ?>
</div>
