<?php
    $this->display("elements/header.phtml", array(
        'title'=> WEB_TITLE.$h5gameArr['name'],
        'addNav' => '1',
        'addStyle' => array('h/game/detail.css'),
        'addTag' => array('<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>')
    ));
?>
<div class="container">
    <div class="mod-game module">
        <input id="gid" type="hidden" value="<?php echo $h5gameArr['id'];?>"/>
        <input id="gameName" type="hidden" value="<?php echo $h5gameArr['name'];?>" />
        <input id="shareImgUrl" type="hidden" value="<?php echo URL_IMAGE.$h5gameArr['logo'];?>" />
        <div class="detail">
            <span class="pic"><img src="<?php echo URL_IMAGE.$h5gameArr['logo'];?>" alt=""></span>
            <span class="cont">
                <h2 class="name"><?php echo $h5gameArr['name'];?></h2>
                <span class="txt"><?php echo $h5gameArr['intro']; ?></span>
            </span>
            <span id="collect" class="btn-collect<?php echo ($h5gameArr['collection'] == 0)? '':' btn-disabled';?>" data-hascollect="<?php echo ($h5gameArr['collection'] == 0) ? 0:1;?>"><i class="love"></i><i class="redheart"></i><span class="txt"><?php echo ($h5gameArr['collection'] == 0)? '收藏':'已收藏';?></span></span>
        </div>
        <a class="btn-start" href="/<?php echo $h5gameArr['id']; ?>.html">开始游戏</a>
    </div>
    <?php if(isset($h5giftArr) && $h5giftArr): ?>
    <div class="mod-gift module">
        <div class="bd">
            <ul>
                <?php foreach ($h5giftArr as $list):?>
                <li class="item">
                    <a href="/gift/detail/?id=<?php echo $list->getId();?>">
                        <span class="txt"><?php echo $list->getName(); ?></span>
                        <span class="btn">领取</span>
                    </a>
                </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
    <?php endif; ?>
    <div class="mod-intro module">
        <div class="hd"><?php echo $h5gameArr['name'];?>介绍</div>
        <div class="bd">
            <div id="introCont" class="hide-cont">
                <?php echo str_replace(chr(10), '<br/>', $h5gameArr['description']); ?>
            </div>
            <div id="hidIntro" class="hid-intro">
                <?php echo str_replace(chr(10), '<br/>', $h5gameArr['description']); ?>
            </div>
            <div id="showAll" class="show-article hide">全文</div>
        </div>
    </div>
    <?php if($h5gameArr['pic']):?>
    <div class="mod-swiper">
        <div class="swiper-container">
            <div id="demo-test-gallery" class="demo-gallery swiper-wrapper">
                <?php foreach (explode(',', $h5gameArr['pic']) as $img){?>
                <a href="<?php echo URL_IMAGE.$img;?>" class="demo-gallery__img--main swiper-slide">
                    <img class="pic-show" src="<?php echo URL_IMAGE.$img;?>" alt="" />
                    <img class="pic-hidden" src="<?php echo URL_IMAGE.$img;?>" alt="" />
                </a>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <?php if(isset($h5noticeArr) && $h5noticeArr): ?>
    <div class="mod-notice module">
        <div class="hd">活动公告</div>
        <div class="bd">
            <ul>
            <?php foreach ($h5noticeArr as $notice):?>
                <li class="item">
                    <a href="/notice/detail/?id=<?php echo $notice->getId();?>">
                        <div class="img"><img src="<?php echo URL_IMAGE.$notice->getThumb();?>" alt=""></div>
                        <div class="info">
                            <?php echo $notice->getTitle();?>
                            <span class="time"><?php echo date("m-d", strtotime($notice->getAddtime()));?></span>
                        </div>
                    </a>
                </li>
            <?php endforeach;?>
            </ul>
        </div>
    </div>
    <?php endif; ?>
    <!-- 图片画廊 -->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="pswp__bg"></div>
        <div class="pswp__scroll-wrap">
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>
            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <div class="pswp__counter"></div>
                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div>
                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>
                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if($isFromWeixin):?>
<script type="text/javascript">
    wx.config({
        appId: '<?php echo $jsConfig['appId']?>', // 必填，公众号的唯一标识
        timestamp: '<?php echo $jsConfig['timestamp']?>', // 必填，生成签名的时间戳
        nonceStr: '<?php echo $jsConfig['noncestr']?>', // 必填，生成签名的随机串
        signature: '<?php echo $jsConfig['sign']?>',// 必填，签名，见附录1
        jsApiList: ['onMenuShareTimeline','onMenuShareAppMessage','onMenuShareQQ','onMenuShareWeibo','onMenuShareQZone'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
    });
    wx.error(function(res) {
        console.log(res);
    });
</script>
<?php endif;?>
<?php
    $this->display("elements/footer.phtml", array(
        'addScript' => array('h/game/detail.js')
    ));
?>
