<?php
    $this->display("elements/header.phtml", array(
        'title'=> '',
        'addStyle' => array()
    ));
?>
<div class="container">
    <iframe id="myIframe" src="<?php echo $this->gameUrl; ?>" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="auto"></iframe>
</div>
<?php
    $this->display("elements/footer.phtml", array(
        'addScript' => array()
    ));
?>
