<?php
    $this->display("elements/header.phtml", array(
        'title'=> WEB_TITLE.$gameModel->getName(),
        'addStyle' => array('h/game/play.css'),
        'addTag' => array('<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>')
    ));
?>
<div id="shadeLoad" class="shade-loading">
    <img src="<?php echo URL_IMAGE.'h/public/game-loading-2016805.png';?>">
</div>
<div id="framenav" class="mod-framenav">
    <a href="javascript:;" rel="nofollow" class="return"><span></span>返回游戏</a>游老虎活动中心
</div>
<div id="container" class="container">
    <input id="gameName" type="hidden" value="<?php echo $gameModel->getName();?>" />
    <input id="shareImgUrl" type="hidden" value="<?php echo URL_IMAGE.$gameModel->getLogo();?>" />
    <input id="isActivity" type="hidden" value="<?php echo $isActivity ? 1: 0;?>" />
    <?php if(!IS_APP):?>
    <div id="assistiveTouch" class="mod-assistive-touch">
        <div class="pic-wrap">
            <span class="pic"></span>
        </div>
        <!-- <span class="touch-indicator"></span> -->
        <?php if($redFlag && $isActivity):?>
        <span class="tip">点我领红包</span>
        <?php endif;?>
    </div>
    <?php endif; ?>
    <div id="sidebar" class="modal">
        <div class="modal-dialog">
            <div class="info-panel scrollable">
                <?php if(!$isActivity):?>
                <div class="mod-sign">
                    <ul>
                        <li>
                            <a id="sign" href="javascript:;" rel="nofollow" data-src="<?php echo H5URL.'member/sign/';?>"><img src="<?php echo URL_IMAGE ;?>h/game/sign.png" /></a>
                        </li>
                        <?php if(SHOW_QRCODE):?>
                        <li>
                            <a id="saveGame" href="javascript:;" rel="nofollow"><img src="<?php echo URL_IMAGE ;?>h/game/save.png" /></a>
                        </li>
                        <?php endif;?>
                    </ul>
                </div>
                <?php endif;?>
                <?php if($isActivity):?>
                <?php if(SHOW_QRCODE):?>
                <div id="saveGame" class="mod-save"><img src="<?php echo URL_IMAGE ;?>h/game/save-big.png" /></div>
                <?php endif;?>
                <div id="redpack" class="mod-redpack">
                    <ul>
                        <li class="redpack">
                            <a href="javascript:;" rel="nofollow" data-src="<?php echo H5URL.'tg/redpackage/index/';?>"><span></span>红包</a>
                        </li>
                        <li class="sign<?php echo $isSigned ? ' signed' : '';?>">
                            <a href="javascript:;" rel="nofollow" data-src="<?php echo H5URL.'member/sign/';?>"><?php echo $isSigned ? '今日已签到' : '签到';?></a>
                        </li>
                    </ul>
                    <div class="online-time">今日累计时长：<span id="onlineTime"></span>分钟</div>
                </div>
                <?php endif;?>
                <?php if(isset($lists) && $lists):?>
                <div class="mod-recommend">
                    <?php if(!$isActivity):?>
                    <div class="hd">
                        <span class="inner"><span class="txt">推荐游戏</span></span>
                    </div>
                    <?php endif;?>
                    <div class="bd">
                        <ul class="list">
                        <?php foreach ($lists as $key => $list):?>
                            <li class="list-item">
                                <a href="/<?php echo $list['id']; ?>.html">
                                    <p class="pic"><img src="<?php echo URL_IMAGE.$list['logo']; ?>"></p>
                                    <p class="txt"><?php echo $list['name']; ?></p>
                                </a>
                            </li>
                            <?php if ($key > 1 && ($key + 1) % 3 == 0 && $key+1!=count($lists)): ?>
                            </ul>
                            <ul class="list">
                            <?php endif; ?>
                        <?php endforeach;?>
                        </ul>
                    </div>
                </div>
                <?php endif;?>
                <div class="more"><a href="/">更多【<span>游老虎</span>】游戏</a></div>
                <?php if(SHOW_QRCODE):?>
                <div class="kefu">
                    <div class="title">联系客服</div>
                    <div class="code"><img src="<?php echo URL_IMAGE?>h/public/code.png"></div>
                    <div class="tip">长按二维码识别<br/>或搜索关注公众号“游老虎”</div>
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
    <div id="codeBox" class="code-box-wrap">
        <div class="inner">
            <div class="title">关注“游老虎”</div>
            <div class="code"><img src="<?php echo URL_IMAGE?>h/public/code.png"></div>
            <div class="tip">长按二维码识别<br/>或搜索关注公众号 “ <span class="sc">游老虎</span> ”</div>
            <div class="close"></div>
        </div>
    </div>
    <?php if(!IS_APP):?>
    <div id="exitGameBox" class="game-box-wrap">
        <div class="inner">
            <div class="title"><?php echo $isFromWeixin ? '更多好游戏尽在游老虎' : '真的要退出吗？';?><span class="close"></span></div>
            <?php if($isFromWeixin):?>
            <ul class="cont">
                <?php foreach($windows as $window):?>
                <li><a href="/<?php echo $window['id'] ?>.html"><img data-src="<?php echo URL_IMAGE.$window['logo']; ?>" alt="<?php echo $window['name']?>"><span class="txt"><?php echo $window['name']?></span></a></li>
                <?php endforeach;?>
                <li><a href="/"><span class="logo"></span><span class="txt">更多游戏</span></a></li>
            </ul>
            <?php else:?>
            <div class="exit-tip">记得把我添加到书签<br/>下次就能直接回到游戏哦~</div>
            <?php endif;?>
            <div class="box-footer">
                <div class="ft-inner">
                    <a class="btn btn-keep" href="javascript:;" rel="nofollow">继续游戏</a>
                    <a class="btn btn-leave" href="javascript:;" rel="nofollow">离开游戏</a>
                    <span class="checkbox">今日不再提示</span>
                </div>
            </div>
        </div>
    </div>
    <?php endif;?>
    <iframe id="myIframe" src="<?php echo $this->gameUrl; ?>" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="auto" style="display: block;margin: 0;padding: 0;vertical-align: bottom;"></iframe>
</div>
<?php if($isFromWeixin):?>
<script type="text/javascript">
    wx.config({
        appId: '<?php echo $jsConfig['appId']?>', // 必填，公众号的唯一标识
        timestamp: '<?php echo $jsConfig['timestamp']?>', // 必填，生成签名的时间戳
        nonceStr: '<?php echo $jsConfig['noncestr']?>', // 必填，生成签名的随机串
        signature: '<?php echo $jsConfig['sign']?>',// 必填，签名，见附录1
        jsApiList: ['chooseWXPay','onMenuShareTimeline','onMenuShareAppMessage','onMenuShareQQ','onMenuShareWeibo','onMenuShareQZone','closeWindow'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
    });
    wx.error(function(res) {
        console.log(res);
    });
</script>
<?php endif;?>
<?php
    $this->display("elements/footer.phtml", array(
        'addScript' => array('h/game/play.js')
    ));
?>
