<?php
    $this->component('head')
        ->setStyles('public/daterangepicker-bs3.css')
        ->setHeadScripts('public/index.js')
        ->setFootScripts('public/public.js')
?>

<body class="page-body loaded">
    <div class="page-container">
        <div class="sidebar-menu">
            <header class="logo-env">
                <div class="logo">
                    <img src="<?php echo URL_IMAGE.'logo.png'?>" height="32">
                </div>
                <div class="sidebar-collapse">
                    <a href="#" class="sidebar-collapse-icon with-animation">
                        <i class="entypo-menu"></i>
                    </a>
                </div>
                <div class="sidebar-mobile-menu visible-xs">
                    <a href="#" class="with-animation">
                        <i class="entypo-menu"></i>
                    </a>
                </div>
            </header>
            <ul id="main-menu">
                <?php foreach($menus as $menu): ?>
                <li class="root-level<?php echo $menu['children'] ? ' has-sub' : NULL; ?>">
                    <a href="<?php echo $menu['url'] ?>"><i class="<?php echo $menu['icon'] ?>"></i><span><?php echo $menu['name'] ?></span></a>
                    <?php if($menu['children']): ?>
                    <ul>
                        <?php foreach($menu['children'] as $children): ?>
                        <li>
                            <a href="<?php echo $children['url'] ?>"><span><?php echo $children['name'] ?></span></a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="main-content">
            <div class="row">
                <div class="col-md-6 col-sm-8 clearfix">
                    <ul class="user-info pull-left pull-none-xsm">
                        <li class="profile-info dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="<?php echo URL_IMAGE.'avatar.jpg'?>" alt="" class="img-circle" width="44">
                                <span>超级管理员</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="caret"></li>
                                <li>
                                    <a href="#">
                                        <i class="entypo-user"></i>编辑用户
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="entypo-mail"></i>消息管理
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-4 clearfix hidden-xs">
                    <ul class="list-inline links-list pull-right">
                        <li>
                            <a href="#sample-modal-message" data-toggle="modal">
                                <i class="entypo-chat"></i>发送消息
                            </a>
                        </li>
                        <li class="sep"></li>
                        <li>
                            <a href="#sample-modal-announcement" data-toggle="modal" class="addAnnouBtn">
                                <i class="entypo-chat"></i>发布公告
                            </a>
                        </li>
                        <li class="sep"></li>
                        <li>
                            <a href="/logout/">
                                用户退出<i class="entypo-logout right"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12" id="layout">
                    <?php echo $body; ?>
                </div>
            </div>
        </div>
    </div>

    <!-- 消息对话框 -->
    <div class="modal fade" id="sample-modal-message">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">发送消息</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group"><div class="help-block"></div></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-field1" class="control-label">用户名</label>
                                <input id="add-field1" type="text" class="form-control" name="target_id">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-field2" class="control-label">消息内容</label>
                                <textarea id="add-field2" class="form-control autogrow" name="content"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-info">确定</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 公告对话框 -->
    <div class="modal fade" id="sample-modal-announcement">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">发布公告</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group"><div class="help-block"></div></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-field2" class="control-label">发布&nbsp;: &nbsp;</label>
                                <input id="announ-field3" type="radio" name="announ_release" value="0" checked="checked"> 否&nbsp; &nbsp;
                                <input id="announ-field3" type="radio" name="announ_release" value="1"> 是
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-field2" class="control-label">目标&nbsp;: &nbsp;</label>
                                <input id="announ-field3" type="radio" name="announ_release_to" value="0" checked="checked"> 所有&nbsp; &nbsp;
                                <input id="announ-field3" type="radio" name="announ_release_to" value="1"> 渠道(c) &nbsp; &nbsp;
                                <input id="announ-field3" type="radio" name="announ_release_to" value="2"> 厂商(f)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-field1" class="control-label">标题</label>
                                <input id="announ-field1" type="text" class="form-control" name="announ_title">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-field2" class="control-label">内容</label>
                                <textarea id="announ-field2" class="form-control" rows="10" name="announ_content"></textarea>
                            </div>
                            <span>链接格式：[显示名称](链接地址)</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="announcement_id" value="0">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-info">确定</button>
                </div>
            </div>
        </div>
    </div>
</body>
<?php $this->component('foot')?>