<div class="sidebar-menu" style="min-height: 139px;">
	<header class="logo-env">
		<div class="logo">
			<a href="javascript:;"><img width="120" alt="Logo"
				src="<?php echo WEB_IMAGE;?>logo3.png"></a>
		</div>
		<div class="sidebar-collapse">
			<a class="sidebar-collapse-icon with-animation" href="javascript:;">
				<i class="entypo-menu"></i>
			</a>
		</div>
	</header>
	<div id="mainClass" class="main-class">
		<?php foreach($menus as $menu):?>
		<p <?php echo strcasecmp(MODULE_NAME, $menu['module']) ? NULL : 'class="curr"';?>>
			<span><?php echo $menu['name'];?> </span>
		</p>
		<?php endforeach;?>
	</div>
	<?php foreach($menus as $menu):?>
	<ul class="main-menu <?php echo strcasecmp(MODULE_NAME, $menu['module']) ? NULL : 'block';?>">
		<?php if(isset($menu['children'])):foreach($menu['children'] as $value):?>
		<li class="root-level has-sub active opened">
			<a href="<?php echo $value['url'];?>"> <i class="<?php echo $value['icon']?>"></i><span><?php echo $value['name'];?></span></a>
			<?php if(isset($value['children'])):foreach($value['children'] as $last):?>
			<ul class="<?php echo strcasecmp(CONTROLLER_NAME, $value['controller']) ? NULL : 'visible';?>">
				<li>
					<a href="<?php echo $last['url']?>"> <span><?php echo $last['name'];?></span></a>
				</li>
			</ul>
			<?php endforeach;endif;?>
		</li>
		<?php endforeach;endif;?>
	</ul>
	<?php endforeach;?>
</div>