<?php if(!$pagitor['over']):?>
<div class="text-right">
<nav>
  <ul class="pagination">
  	<!-- 上一页start -->
  	<li>
      <a href="<?php echo isset($pagitor['prev']) ? $pagitor['url'].$pagitor['prev'] : 'javascript:;'?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
	<!-- 上一页end -->  
    <!-- 中间区间页数start -->
	<?php for(;$pagitor['start']<$pagitor['end']; $pagitor['start']++):?>
	<li <?php echo ($pagitor['start'] == $pagitor['page']) ? "class='active'" : NULL?>>
		<a href="<?php echo ($pagitor['start'] == $pagitor['page']) ? 'javascript:;' : $pagitor['url'].$pagitor['start']?>"><?php echo $pagitor['start'];?></a>
	</li>
	<?php endfor;?>
	<!-- 中间区间页数end -->
	<!-- 下一页start -->
	<li>
      <a href="<?php echo isset($pagitor['next']) ? $pagitor['url'].$pagitor['next'] : 'javascript:;'?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
	<!-- 下一页end -->
  </ul>
</nav>
</div>
<?php endif;?>