<?php
	$this->setTitle('游老虎_金币充值')
		->setStyles('h/pay/recharge.css')
		->setFootScripts('h/pay/recharge.js')
		->setValue('nav', TRUE)
		->setTabs('<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>');

	$checked = $device == 'weixin';
?>
<div class="container">
	<div class="mod-recharge">
		<div class="module cnt-amount">
			<div class="hd">选择金额</div>
			<div class="bd">
				<ul id="amountList">
					<li class="amount-item" price="10"><span class="amount">10</span>元</li>
					<li class="amount-item active" price="20"><span class="amount">20</span>元</li>
					<li class="amount-item" price="50"><span class="amount">50</span>元</li>
					<li class="amount-item" price="100"><span class="amount">100</span>元</li>
					<li class="amount-item" price="500"><span class="amount">500</span>元</li>
					<li class="amount-item" price="0"><input id="otherAmount" class="inpt" type="tel" maxlength="6" placeholder="其他金额" autocomplete="off" onpaste="return false;" onkeypress="if(event.keyCode<48 || event.keyCode>57)event.returnValue=false;" /></li>
				</ul>
			</div>
		</div>
		<div class="module cnt-pay">
			<div class="hd">选择支付方式</div>
			<div class="bd">
				<ul id="payList">
					<li class="pay-item<?php if(!$checked):?> selected<?php endif;?>" data-payname="alipay"><span class="pay-icon pay-alipay"></span><span class="txt">支付宝</span><span class="ui-checkbox"></span></li>
					<?php if(in_array($device, array('web', 'weixin'))):?>
					<li class="pay-item<?php if($checked):?> selected<?php endif;?>" data-payname="wxpay"><span class="pay-icon pay-wechat"></span><span class="txt">微信支付</span><span class="ui-checkbox"></span></li>
					<?php endif;?>
					<!-- <li class="pay-item" data-payname="bankpay"><span class="pay-icon pay-upcash"></span><span class="txt">银联支付</span><span class="ui-checkbox"></span></li> -->
				</ul>
			</div>
		</div>
		<div class="pay-footer">
			<div class="inner">
				<div class="payment">总计：<span id="iAmount" class="txt-red"></span>元（<span id="iCoin" class="txt-red"></span>金币）</div>
            	<input id="submitBtn" class="submit-btn" type="submit" data-value="确认支付" value="确认支付" />
			</div>
		</div>
		<input type="hidden" id="hidPrice" name="price" value="20" />
	</div>
</div>