<div class="modal fade" id="tip-message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-sm tip-modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
				<button v-if="!url" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title">{{ title }}</h4>
            </div>
            <div class="modal-body">
                <p style="font-size:20px !important" class="result-message">{{{ message }}}</p>
				
            </div>
        	 <div v-if="url" class="modal-footer">
		        <a v-bind:href="url" class="btn btn-success">确定</a>
		     </div>
        </div>
    </div>
</div>

<script>
var alertTip = new Vue({
	el : '#tip-message',
	data : {
		title : '消息提示',
		message : '',
		url : ''
	},
	methods : {
		show : function(title, message, url) {
			this.title = title;
			this.message = message;
			this.url = url;
			$('#tip-message').appendTo('body').modal('show');
		},
		hide : function(title, message, url) {
			this.title = title;
			this.message = message;
			this.url = url;
			$('#tip-message').appendTo('body').modal('hide');
		}
	}
});
</script>