<script src="<?php echo URL_SCRIPT; ?>public/vue.min.js"></script>
<script src="<?php echo URL_SCRIPT; ?>public/main-gsap.js"></script>
<script src="<?php echo URL_SCRIPT; ?>public/moment.min.js"></script>
<script src="<?php echo URL_SCRIPT; ?>public/joinable.js"></script>
<script src="<?php echo URL_SCRIPT; ?>public/resizeable.js"></script>
<script src="<?php echo URL_SCRIPT; ?>public/neon-api.js"></script>
<script src="<?php echo URL_SCRIPT; ?>public/neon-custom.js"></script>
<?php foreach($this->getFootScripts() as $script):?>
<script type="text/javascript" src="<?php echo URL_SCRIPT.$script?>"></script>
<?php endforeach;?>
</html>

