<script src="<?php echo URL_SCRIPT . 'public/main-gsap.js' ?>"></script>
<script src="<?php echo URL_SCRIPT . 'public/bootstrap.js' ?>"></script>
<script src="<?php echo URL_SCRIPT . 'public/resizeable.js' ?>"></script>
<script src="<?php echo URL_SCRIPT . 'public/neon-api.js' ?>"></script>
<script src="<?php echo URL_SCRIPT . 'public/jquery.validate.min.js' ?>"></script>

<?php foreach($this->getFootScripts() as $script):?>
<script type="text/javascript" src="<?php echo URL_SCRIPT.$script?>"></script>
<?php endforeach;?>
<script src="<?php echo URL_SCRIPT . 'public/neon-custom.js' ?>"></script>
</html>