<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="wap-font-scale" content="no">
    <link rel="dns-prefetch" href="//static.youlaohu.com" />
    <?php if($canonical = $this->getCanonical()):?>
    <link rel="canonical" href="<?php echo $canonical;?>"/>
    <?php endif;?>
    <title><?php echo $this->getTitle(); ?></title>
    <?php foreach($this->getMetas() as $name=>$content):?>
	<meta name="<?php echo $name;?>" content="<?php echo $content;?>">
	<?php endforeach;?>
	<?php foreach($this->getStyles() as $style):?>
	<link rel="stylesheet" type="text/css" href="<?php echo WEB_STYLE . $style; ?>">
	<?php endforeach;?>
    <link rel="shortcut icon" href="<?php echo WEB_IMAGE;?>public/favicon.ico">
    <link href="<?php echo WEB_STYLE.'h/common/style.css?v='.WEB_VERSION; ?>" rel="stylesheet" type="text/css"/>
    <script type="text/javascript">
        var PageConfig = {
            myUrl :"/member/",
            imgUrl:'<?php echo WEB_IMAGE;?>'
        };
        (function(win){
            var eventType = "resize";//"onorientationchange" in win ? "orientationchange" : "resize";//解决微信浏览器下旋转屏幕时宽度计算错误的问题,部分安卓机子也会出问题
            var resizeFun = function(){
                var htmlEle = win.document.documentElement;
                var width = Math.min(htmlEle.clientWidth, 1080);
                htmlEle.style.fontSize = width / 10.8 + "px";
            };
            resizeFun();
            win.addEventListener(eventType, resizeFun, false);
        })(window);
    </script>
</head>