<?php if(!$pagitor['over']):?>
<div class="row">
	<div class="col-xs-6 col-left">
		<div class="dataTables_info">
			<span><?php echo $pagitor['count']; ?></span> 条, 共 <span><?php echo $pagitor['pageTotal']; ?></span> 页
		</div>
	</div>
	<div class="col-xs-6 col-right">
		<div class="dataTables_paginate paging_bootstrap">
			<ul class="pagination pagination-sm">
				<li class="first"><a href="<?php echo isset($pagitor['prev']) ? $pagitor['url'].$pagitor['prev'] : 'javascript:;'?>" aria-label="Previous"> <i class="entypo-to-start"></i></a></li>
				<?php for(;$pagitor['start']<$pagitor['end']; $pagitor['start']++):?>
				<?php endfor;?>
				<li <?php echo ($pagitor['start'] == $pagitor['page']) ? "class='active'" : NULL?>><a href="<?php echo ($pagitor['start'] == $pagitor['page']) ? 'javascript:;' : $pagitor['url'].$pagitor['start']?>"><?php echo $pagitor['start'];?></a></li>
				<li class="last"><a href="<?php echo isset($pagitor['next']) ? $pagitor['url'].$pagitor['next'] : 'javascript:;'?>" aria-label="Next"> <i class="entypo-to-end"></i></a></li>
			</ul>
		</div>
	</div>
</div>
<?php endif;?>