<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<title>店铺-光年设计表现</title>
	<link rel="stylesheet" type="text/css" href="<?php echo WWW_STYLE?>bootstrap.min.css">
  	<link rel="stylesheet" type="text/css" href="<?php echo WWW_STYLE?>base.css">
  	<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
	<script src="<?php echo WWW_SCRIPT;?>bootstrap.min.js"></script>
	<script src="<?php echo WWW_SCRIPT;?>active.js"></script>
</head>
<body>
<header>
    <div class="container">
      <h1><a class="block" href="#">光年设计表现</a></h1>
    </div>
    <div class="title-1">
      <nav class="navbar navbar-inverse navbar-static-top" >
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="nav-x"><a href="/shop/">店铺首页</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="/shop/service/">服务项目</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="/shop/list/">作品展示</a></li>
            <li class="nav-x">|</li>
            <li class="nav-x"><a href="/shop/record/">交易记录</a></li>
          </ul>
        </div>
      </nav>
    </div>
</header>