<?php $this->commonLayout('head', array('styles'=>array('login.css')))?>
<body class="page-body login-page login-form-fall loaded login-form-fall-init">
	<div class="login-container">
		<div class="login-header login-caret">
			<div class="login-content">
				<a href="javascript:;" class="logo"> <img
					alt="Logo" src="<?php echo WEB_IMAGE ;?>logo3.png">
				</a>
				<p class="description">Eny.Inc</p>
			</div>
		</div>
		<div class="login-form">
			<div class="login-content">
				<form id="form_login" role="form" method="post">
					<div class="form-group">	
						<div class="input-group focused">
							<div class="input-group-addon"><i class="entypo-user"></i></div>
							<input type="email" placeholder="账号" id="username" name="email" class="form-control" tabindex="1">
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="entypo-key"></i></div>
							<input type="password" placeholder="密码" id="password" name="password" class="form-control" tabindex="2">
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="entypo-feather"></i></div>
							<input id="checkCode" class="form-control" autocomplete="off" type="text" name="captcha[code]" tabindex="3" placeholder="验证码" maxlength="4">
							<img class="checkImg" src="/www/image/captcha" width="122" height="50">
						</div>
					</div>
					<div class="form-group">
						<button class="btn btn-primary btn-block btn-login" type="submit">登录</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
<?php $this->commonLayout('foot')?>