<?php $this->setTitle('游老虎_每日签到')->setStyles('h/member/sign/index.css')->setValue('nav', 1); ?>
<div class="container">
    <div class="mod-sign">
        <p class="total">签到累计获得</p>
        <span class="price"><span id="tcoin"><?php echo $goldcoin; ?></span>金币</span>
        <a id="straBtn" href="javascript:;" class="strategy">签到攻略</a>
        <a href="javascript:;" id="signBtn" class="btn">
             <input type="hidden" id="signDate" data-date="<?php echo implode(",", $detailArr);?>"/>
            <?php if($flag == 1): //判断是否签到 ?>
            <span class="sign" data-issign="1">已签到</span>
            <?php else: ?>
            <span class="sign" data-issign="0">签到</span> 
            <?php endif; ?>
            <span class="continuity">连续<em id="day"><?php echo $count; ?></em>天</span>
        </a>
    </div>
    <?php if(isset($gameArr) && $gameArr): ?>
    <div class="mod-games">
        <div class="hd">推荐游戏</div>
        <div id="gameList" class="bd">
            <ul>
            <?php foreach ($gameArr as $game):?>
                <li class="j-link" data-gameid="<?php echo $game['id']?>">
                    <div class="pic"><img src="<?php echo URL_IMAGE.$game['logo'];?>" alt=""></div>
                    <div class="cont">
                        <h3><?php echo $game['name']; ?><?php if($game['hasGift']):?><span class="gift">礼包</span><?php endif;?><?php if($game['is_recommend']):?><span class="hot">热门</span><?php endif;?>
                        </h3>
                        <p class="description"><?php echo $game['intro']; ?></p>
                    </div>
                    <a href="/<?php echo $game['id']; ?>.html" class="button" target="_top"><span class="btn-start">进入</span></a>
                </li>
            <?php endforeach;?>
            </ul>
        </div>
    </div>
    <?php endif;?>
    <div id="sign" class="mod-calendar">
        <div class="head">签到成功</div>
        <a href="javascript:;" id="close" class="close"></a>
        <p class="title">连续签到 <em id="iday"><?php echo $count; ?></em> 天，今日已领<span id="icoin"><?php echo $oneCoin;?></span>金币</p>
        <div class="thead">
            <table>
                <tr>
                    <td>日</td>
                    <td>一</td>
                    <td>二</td>
                    <td>三</td>
                    <td>四</td>
                    <td>五</td>
                    <td>六</td>
                </tr>
            </table>
        </div>
        <div class="table">
            <table>
                <tbody id="table"></tbody>
            </table>
        </div>
        <!-- <div class="pic"></div> -->
    </div>
    <div id="mask" class="mod-mask"></div>
    <div id="strategy" class="mod-strategy hide">
        <div class="inner">
            <div class="title">签到攻略</div>
            <div class="cont">首次签到奖励<span class="txt-red">1</span>金币<br/>后续连续签到奖励将以每日<span class="txt-red">1</span>金币递增<br/>单日签到最高奖励封顶<span class="txt-red">5</span>金币</div>
            <a id="sclose" class="btn-close" href="javascript:;" class="close">关闭</a>
        </div>
    </div>
</div>
<?php $this->setValue('footer', 1)->setFootScripts('h/member/sign/index.js'); ?>