<?php
    $this->setTitle('游老虎_商务合作')
        ->setValue('usrNav', TRUE)
        ->setStyles('h/help/business.css');
?>
<div class="container">
    <div class="mod-business">
        <dl class="cont per1">
            <dt>商务合作</dt>
            <dd>
                <p class="desc">欢迎各微信公众号、渠道商、网站等与我方洽谈H5网页游戏CPS合作；欢迎各H5游戏厂商接入我方平台，合作方式不限。</p>
                <p>联系人：危先生</p>
                <p>联系QQ：1071353377</p>
                <p>联系邮箱：wc@5755.com</p>
            </dd>
        </dl>
         <dl class="cont per2">
            <dt>推广合作</dt>
            <dd>
                <p class="desc">品牌及联盟广告投放：欢迎各品牌网站代理及网络联盟恰谈广告推广合作。</p>
                <p>联系人：危先生</p>
                <p>联系QQ：1071353377</p>
                <p>联系邮箱：wc@5755.com</p>
            </dd>
        </dl>
         <dl class="cont per3">
            <dt>友情链接</dt>
            <dd>
                <p>欢迎相关行业站点互换友情链接。</p>
                <p>QQ：89932916</p>
            </dd>
        </dl>
    </div>
</div>