<?php
    $this->setTitle('游老虎_联系我们')
        ->setValue('usrNav', TRUE)
        ->setStyles('h/help/contact.css');
?>
<div class="container">
    <div class="mod-contact">
        <ul>
            <li class="person1">
                <p class="tit">客服芳芳</p>
                <p class="contact">QQ：1073353388</p>
            </li>
            <li class="person2">
                <p class="tit">客服美美</p>
                <p class="contact">QQ：1073353399</p>
            </li>
            <li class="person3">
                <p class="tit">客服邮箱</p>
                <p class="contact">kf@5755.com</p>
            </li>
        </ul>
    </div>
</div>