<?php
    $this->setTitle('游老虎_反馈意见')
        ->setValue('usrNav', TRUE)
        ->setStyles('h/help/feedback.css')
        ->setFootScripts('h/help/feedback.js');
?>
<div class="container">
    <div class="mod-feedback">
        <div class="info">
            <h2>您的意见反馈</h2>
            <div class="cont">
                <textarea id="textarea" class="inpt" placeholder="请输入您的反馈意见"></textarea>
                <p class="num">还可输入<span id="count">160</span>字</p>
            </div>
        </div>
        <div class="info">
            <h2>联系方式</h2>
            <div class="email">
                <input id="contact" class="input-model" type="text" name="email" value="" placeholder="请输入电子邮箱 / 手机号" autocapitalize="off" />
                <span class="clear-input"></span>
            </div>
        </div>
        <div class="btn"><a id="submitBtn" class="submit-btn button-disabled" href="javascript:;" rel="nofollow">提交</a></div>
    </div>
</div>