<?php
    $this->setTitle('帮助中心_游老虎')->setValue('usrNav', TRUE)->setStyles('h/help/index.css'); ?>
<div class="container">
    <div class="mod-help">
        <ul>
            <li><a href="/help/message/">系统消息</a></li>
            <li><a href="/help/contact/">联系我们</a></li>
            <li><a href="/help/business/">商务合作</a></li>
            <li><a href="/help/feedback/">意见反馈</a></li>
            <li><a href="/help/question/">常见问题</a></li>
        </ul>
    </div>
</div>