<?php
    $this->setTitle('游老虎_系统消息')
        ->setValue('usrNav', TRUE)
        ->setStyles('h/help/message.css');
?>
<div class="container">
	<?php if(isset($lists) && $lists):?>
    <div class="mod-message">
        <ul>
        	<?php foreach($lists as $key=>$value):?>
            <li class="item">
            	<a href="/help/message/<?php echo $value['id']?>.html">
                    <p class="datetime"><?php echo date('m-d', $value['uptime']);?></p>
               		<p class="cont"><?php echo $value['title']?></p>
            	</a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php else: ?>
        <?php $this->setValue('notify', '还没有消息哦！')->component('empty'); ?>
    <?php endif;?>
</div>