<?php
    $this->display("elements/header.phtml", array(
        'title'=> $articleModel->getTitle().'-'.WEB_TITLE,
        'addUsrNav' => '1',
        'addStyle' => array('h/help/msgdetail.css')
    ));
?>
<div class="container">
    <div class="mod-detail">
        <div class="hd">
            <h2><?php echo $articleModel->getTitle(); ?></h2>
            <p class="time"><?php echo date('Y-m-d H:i:s', $articleModel->getUptime());?></p>
        </div>
        <div class="bd">
        	<?php echo $articleModel->getContent(); ?>
        </div>
    </div>
</div>
<?php
    $this->display("elements/footer.phtml");
?>