<?php
    $this->setTitle('游老虎_常见问题')
        ->setValue('usrNav', TRUE)
        ->setStyles('h/help/question.css')
        ->setFootScripts('h/help/question.js');
?>
<div class="container">
	<?php if($questions):?>
    <div class="mod-question">
        <ul id="j-qa">
        	<?php foreach($questions as $question):?>
            <li>
                <p class="question"><?php echo $question['question']; ?></p>
                <div class="answer"><?php echo str_replace(chr(10), '<br/>', $question['answer']); ?></div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif;?>
</div>