<?php $this->layout('header.phtml', array('title'=>'enychen.Inc_首页'))?>
<body class="page-body loaded">
	<div class="page-container">
		<?php $this->display('layout/left.phtml')?>
		<div class="main-content" style="min-height: 947px;">
			<?php $this->display('layout/user.phtml')?>
			<div class="navbar-collapse"></div>
			<div class="dataTables_wrapper"></div>
		</div>
	</div>
</body>
<?php $this->layout('footer.phtml')
?>