<?php $this->commonLayout('header');?>
<h3>用户列表</h3>
<div class="navbar-collapse">
	<form class="navbar-form navbar-left" role="search">
		<div class="form-group">
			UID：<input type="text" name="uid" value="" class="form-control" placeholder="UID"> 
			昵称：<input type="text" name="nickname" value="" class="form-control" placeholder="Search"> 
			oauth_id：<input type="text" size="35" name="oid" value="" class="form-control" placeholder="Search"> 
			<span><input type="text" name="start_time" class="form-control datepicker dateStart" placeholder="开始时间" value=""></span>
			<span> - <input type="text" name="end_time" class="form-control datepicker dateEnd" placeholder="结束时间" value=""></span>
		</div>
		<button type="submit" class="btn btn-default">Search</button>
	</form>
</div>
<div class="dataTables_wrapper">
	<table id="dataTable-user"
		class="table table-condensed table-bordered table-hover">
		<thead>
			<tr>
				<th class="text-center">UID</th>
				<th>昵称</th>
				<th title="绑定">Bind</th>
				<th>Email</th>
				<th>Mobile</th>
				<th>来源标识</th>
				<th>Reg Time</th>
				<th>Login Time</th>
				<th>Login IP</th>
				<th>可用金币</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="text-center">77284</td>
				<td>18755007055</td>
				<td><i class="entypo-mobile active"></i> <i
					class="entypo-qq disabled"></i> <i class="fa fa-weibo disabled"></i>
					<i class="entypo-mail disabled"></i> <i
					class="fa fa-weixin disabled"></i></td>
				<td></td>
				<td><a
					href="http://www.ip138.com:8080/search.asp?action=mobile&amp;mobile=18755007055"
					target="_blank"> 18755007055 </a></td>
				<td>yy138ios用小图(200003)</td>
				<td>2016-07-20 14:55:34</td>
				<td>2016-07-20 14:55:34</td>
				<td><a href="http://ip138.com/ips138.asp?ip=112.90.236.119"
					target="_blank"> 112.90.236.119 </a></td>
				<td>0</td>
				<td class="text-center"><a class="btn btn-blue"
					href="http://op.youlaohu.com/admin/user/edit/?uid=77284">修改</a>&nbsp;
					<a data-user-id="77284" data-disable="false"
					class="js-btn btn btn-sm btn-red" href="javascript:void(0);">禁用</a>
				</td>
			</tr>
			<tr>
				<td class="text-center">77283</td>
				<td>夏末秋凉╮淡抹了谁的年华</td>
				<td><i class="entypo-mobile disabled"></i> <i
					class="entypo-qq active"></i> <i class="fa fa-weibo disabled"></i>
					<i class="entypo-mail disabled"></i> <i
					class="fa fa-weixin disabled"></i></td>
				<td></td>
				<td></td>
				<td>oicq88等站使用素材(200001)</td>
				<td>2016-07-20 14:54:47</td>
				<td>2016-07-20 14:54:47</td>
				<td><a href="http://ip138.com/ips138.asp?ip=27.44.11.236"
					target="_blank"> 27.44.11.236 </a></td>
				<td>0</td>
				<td class="text-center"><a data-user-id="77283" data-disable="false"
					class="js-btn btn btn-sm btn-red" href="javascript:void(0);">禁用</a>
				</td>
			</tr>
			<tr>
				<td class="text-center">77282</td>
				<td>go--go--go--go</td>
				<td><i class="entypo-mobile disabled"></i> <i
					class="entypo-qq disabled"></i> <i class="fa fa-weibo disabled"></i>
					<i class="entypo-mail disabled"></i> <i
					class="fa fa-weixin disabled"></i></td>
				<td></td>
				<td></td>
				<td>3533ios用小图(200002)</td>
				<td>2016-07-20 14:54:42</td>
				<td>2016-07-20 14:54:42</td>
				<td><a href="http://ip138.com/ips138.asp?ip=60.0.90.48"
					target="_blank"> 60.0.90.48 </a></td>
				<td>0</td>
				<td class="text-center"><a class="btn btn-blue"
					href="http://op.youlaohu.com/admin/user/edit/?uid=77282">修改</a>&nbsp;
					<a data-user-id="77282" data-disable="false"
					class="js-btn btn btn-sm btn-red" href="javascript:void(0);">禁用</a>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<script src="<?php echo WEB_SCRIPT?>bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?php echo WEB_SCRIPT?>common.js"></script>
<?php $this->commonLayout('footer');?>