<?php $this->version='201609081125'?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title><?php echo $data->getTitle().'-'.WEB_TITLE;?></title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="shortcut icon" href="<?php echo URL_IMAGE;?>public/favicon.ico">
    <link href="<?php echo STYLEURL.'h/notice/detail.css?v='.$this->version; ?>" rel="stylesheet" type="text/css"/>
    <?php if($isFromWeixin):?>
    <script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <?php endif;?>
</head>
<body>
    <div class="container">
        <input id="shareTitle" type="hidden" value="<?php echo $data->getTitle();?>" />
        <input id="shareDesc" type="hidden" value="<?php echo $data->getDescription()?>" />
        <input id="sharePic" type="hidden" value="<?php echo URL_IMAGE.$data->getThumb();?>" />
        <div class="mod-notice">
            <h1><?php echo $data->getTitle();?></h1>
            <?php if(!IS_APP):?>
            <p class="info"><span class="time"><?php echo date("Y-m-d", strtotime($data->getAddtime())); ?></span><a class="link" href="/">游老虎</a></p>
            <?php endif;?>
            <?php echo $data->getContent();?>
            <?php if($this->game['gamelink']==1):?>
            <a class="entergame" href="<?php echo $this->game['gameurl'];?>" target="_self" data-gid="<?php echo $this->game['gid'];?>" data-gameurl="<?php echo $this->game['gameurl'];?>" data-gamevertical="<?php echo $this->game['gamevertical'];?>">》进入游戏《</a>
            <?php endif;?>
        </div>
        <?php if(!IS_APP):?>
        <div class="mod-article-footer">
            <a class="read-all" href="<?php echo $data->getLink();?>">阅读原文</a>
            <span class="num">阅读 <?php echo $data->getNumber() > 100000? $data->getNumber().'+': $data->getNumber();?></span>
            <a id="praise" class="praise cancel-like hide" href="javascript:;" rel="nofollow"><?php echo $data->getLikeNum();?></a>
        </div>
        <?php endif;?>
    </div>
    <?php if($isFromWeixin):?>
    <script type="text/javascript">
        wx.config({
            appId: '<?php echo $jsConfig['appId']?>', 
            timestamp: '<?php echo $jsConfig['timestamp']?>', 
            nonceStr: '<?php echo $jsConfig['noncestr']?>', 
            signature: '<?php echo $jsConfig['sign']?>',
            jsApiList: ['onMenuShareTimeline','onMenuShareAppMessage','onMenuShareQQ','onMenuShareWeibo','onMenuShareQZone'] 
        });
        wx.error(function(res) {
            console.log(res);
        });
    </script>
    <?php endif;?>
    <script type="text/javascript" src="<?php echo SCRIPTURL.'lib/jquery-2.2.2.min.js';?>"></script>
    <script type="text/javascript" src="<?php echo SCRIPTURL.'lib/sea.js';?>"></script>
    <script type="text/javascript" src="<?php echo SCRIPTURL.'h/plugins/fastclick.js';?>"></script>
    <script type="text/javascript">
        $(function() {
          FastClick.attach(document.body);
        });
    </script>
    <script>
        seajs.config({
            base:'<?php echo rtrim(SCRIPTURL,'/'); ?>',
            paths: {
                'addScript':'<?php echo rtrim(SCRIPTURL,'/'); ?>'
            },
            map: [
                [ /^(.*?\/script\/(?:src|dist)\/.*?\/.*?\.js$)(?:.*)$/i, '$1?v=<?php echo $this->version;?>']
            ],
            charset: 'utf-8'
        });
        seajs.use('addScript/h/notice/detail.js');
    </script>
    <?php //全站统计代码?>
    <div class="hide">
        <?php echo COUNTCODE;?>
    </div>
</body>
</html>
