<?php if($pagitor['pageTotal'] > 1): ?>
<div class="row">
    <div class="col-xs-6 col-left">
        <div class="dataTables_info">
            <span><?php echo $pagitor['count']?></span> 条,
            共 <span><?php echo $pagitor['pageTotal']?></span> 页
        </div>
    </div>
    <div class="col-xs-6 col-right">
        <div class="dataTables_paginate paging_bootstrap">
            <ul class="pagination pagination-sm">
                <?php if(isset($pagitor['prev'])):?>
                <li class="first">
                    <a href="<?php echo $page['url'],$page['prev']?>">
                        <i class="entypo-to-start"></i>
                    </a>
                </li>
                <?php endif; ?>
                <?php for(;$pagitor['start']<$pagitor['end']; $pagitor['start']++):?>
                <li class="active">
                    <a href="<?php echo $page['url'],$page['start']?>"><?php echo $pagitor['start'];?></a>
                </li>
                <?php endfor;?>
                <?php if(isset($pagitor['last'])):?>
                <li class="last">
                    <a href="<?php echo $page['url'],$page['last']?>">
                        <i class="entypo-to-end"></i>
                    </a>
                </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>