<div class="row">
	<div class="col-md-6 col-sm-8 clearfix">
		<ul class="user-info pull-left pull-none-xsm">
			<li class="profile-info dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="http://op.local.369123.com/admin/user/list/#">
					<img class="img-circle" width="44" alt="" src="<?php echo ADMIN_IMAGE?>50.png">陈晓波</a>
				<ul class="dropdown-menu">
					<li class="caret"></li>
					<li>
						<a href="http://op.local.369123.com/admin/administrator/password/">
							<i class="entypo-lock"></i>
							修改密码
						</a>
					</li>
					<li>
						<a href="http://op.local.369123.com/admin/user/list/#">
							<i class="entypo-doc-text"></i>
							日志
						</a>
					</li>
					<li>
						<a href="http://op.local.369123.com/admin/logout/">
							<i class="entypo-logout"></i>
							退出
						</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>
</div>